language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
#   Pending normalization of HTML output for regressions.
#   - pypy
#   - pypy3
install:
    - pip install .
script:
    - python setup.py test -q
notifications:
    email: false
